# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: notion-backup-build-run

on:
  push:
    branches: [ master ]

  # adds a "run workflow" button to the page
  workflow_dispatch:

  # will be triggered at 00:00 every Sunday
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml --no-transfer-progress

    - name: Start Notion Backup
      run: java -jar ./target/notion-backup-1.0-SNAPSHOT.jar
      env:
        NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
        NOTION_EMAIL: ${{ secrets.NOTION_EMAIL }}
        NOTION_PASSWORD: ${{ secrets.NOTION_PASSWORD }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

        GOOGLE_DRIVE_ROOT_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER_ID }}
        GOOGLE_DRIVE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}
        GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON }}
        GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH }}
       
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}

        NEXTCLOUD_EMAIL: ${{ secrets.NEXTCLOUD_EMAIL }}
        NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}
        NEXTCLOUD_WEBDAV_URL: ${{ secrets.NEXTCLOUD_WEBDAV_URL }}
        
        PCLOUD_ACCESS_TOKEN: ${{ secrets.PCLOUD_ACCESS_TOKEN }}
        PCLOUD_API_HOST: ${{ secrets.PCLOUD_API_HOST }}
        PCLOUD_FOLDER_ID: ${{ secrets.PCLOUD_FOLDER_ID }}

        DOWNLOADS_DIRECTORY_PATH: /tmp/
